# Assignment 4

*Submission From:*

*18EE10043 : Rhitvik Sinha*  
*18EE10062 : Akshat Kumar Gupta*  
*18EE30021 : Pratyush Jaiswal*  
*18EE30029 : Nuruddin Jiruwala*

*Performed in Google Colab*

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Part 1

*Read the .mat files in Python and access the variables.*

In [ ]:
import scipy.io
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso

mat=scipy.io.loadmat('/content/drive/My Drive/ML_datasets/2010rainfall.mat')
mat1=scipy.io.loadmat('/content/drive/My Drive/ML_datasets/2011rainfall.mat')

print(mat.keys())
print(mat1.keys())

data = mat['XR1']
data1 = mat1['XR']

np.shape(data1)

dict_keys(['__header__', '__version__', '__globals__', 'XR1', 'ZR1'])
dict_keys(['__header__', '__version__', '__globals__', 'XR', 'ZR'])


(357, 122)

In [ ]:
ind = list(range(1, 358))
cols = list(range(1, 123))

Train_main_df = pd.DataFrame(data, index = ind, columns = cols)   # 2010 training data
Test_main_df1 = pd.DataFrame(data1, index = ind, columns = cols)    # 2011 testing data

Train_main_df.tail()

1          2    3          4    ...        119       120       121  122
353  15.400000  22.299999  3.6  18.700003  ...  28.000002  1.700000  1.700000  0.0
354  10.266666  14.866666  2.4  12.466667  ...  18.666666  1.133333  1.133333  0.0
355   0.000000   0.000000  0.0   0.000000  ...   0.000000  0.000000  0.000000  0.0
356   0.000000   0.000000  0.0   0.000000  ...   0.000000  0.000000  0.000000  0.0
357   0.000000   0.000000  0.0   0.000000  ...   0.000000  0.000000  0.000000  0.0

[5 rows x 122 columns]

## Part 2

*Use a linear regression model to predict the rainfall XR(s,t) at any location 's' on day 't', using as predictor the rainfall at all other locations on the same day, and also rainfall at the same location on the previous 2 days* `[XR(1,t)....XR(s-1,t), XR(s+1,t),....XR(357,t), XR(s,t-1), XR(s,t-2)]`*. Use 2010 data for training.*

*Build such a model for* `s=42` *(Mumbai),* `s=158` *(Delhi),* `s= 299` *(Kharagpur).*

In [ ]:
def Trainable(Train,s):
    copyt = Train.T             # transpose as working with columns is more suitable/easy
    rainlist = copyt[s].tolist()        # rain at place s for 122 days
    rainone = [0.0]                     # day -1 assumed to be zero
    raintwo = [0.0, 0.0]                # day -1 and -2 assumed to be zero
    # print(rainlist)
    rainone = rainone + rainlist
    raintwo = raintwo + rainlist
    rainone = rainone[:-1]
    raintwo = raintwo[:-2]              # getting t-1 and t-2 data and assuming zero rain at day -1 and -2
    Y_train = copyt[s]
    X_train = copyt.drop(s, axis=1)     # all 122 days data except place s
    X_train['t-1'] = rainone            # adding two cols for the previous days rain at place s
    X_train['t-2'] = raintwo
    return X_train,Y_train

In [ ]:
def Linear(s):
    X_train,Y_train=Trainable(Train_main_df,s)
    print(X_train.shape)
    print(Y_train.shape)
    linreg = LinearRegression()
    linreg.fit(X_train, Y_train)
    return linreg

In [ ]:
Bombay = Linear(42)
Delhi = Linear(158)
Kharagpur = Linear(299)                 #training for three cities

(122, 358)
(122,)
(122, 358)
(122,)
(122, 358)
(122,)


In [ ]:
Test_main_df1.head()                    # 2011 dataset

1    2    3          4    5    6    ...  117  118  119  120  121  122
1  0.0  0.0  0.0   0.000000  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0   0.000000  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  21.500555  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0   0.000000  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0   0.000000  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 122 columns]

### Predicting on test data

In [ ]:
def Predictmodel(model, s):             # model is the trained model and s is the city number
    X_test,Y_test=Trainable(Test_main_df1,s)
    Y_pred = model.predict(X_test)      # predicting on 2011
    Y_pred = [0.0 if x<0 else x for x in Y_pred]# amount of rain cannot be negative, so replace by zero
    return Y_pred

In [ ]:
Y_bombay = Predictmodel(Bombay, 42)
Y_delhi = Predictmodel(Delhi, 158)
Y_kgp = Predictmodel(Kharagpur, 299)
      

Y_bombay_actual = Test_main_df1.T[42]
Y_delhi_actual = Test_main_df1.T[158]
Y_kgp_actual = Test_main_df1.T[299]

## Part 3

*Use the same model to predict the rainfall at these 3 locations on each day of 2011.  Use values in XR as predictors. Compare the results with the true values and compute error for 3 locations separately.*

In [ ]:
from sklearn.metrics import mean_squared_error

rmsbombay = (mean_squared_error(Y_bombay_actual, Y_bombay))
rmsdelhi = (mean_squared_error(Y_delhi_actual, Y_delhi))
rmskgp = (mean_squared_error(Y_kgp_actual, Y_kgp))
print("Bombay error:" + str(rmsbombay))
print("Delhi error:" + str(rmsdelhi))
print("Kgp error:" + str(rmskgp))

Bombay error:1204.7749014858373
Delhi error:448.46136659206354
Kgp error:419.35458442698535


## Part 4

*Repeat the same process using LASSO linear regression. Using the coefficients, identify the top 5 predictors for each of the 3 locations.*

In [ ]:
def Lassoreg(s,p):
    X_train,Y_train=Trainable(Train_main_df,s)
    model = Lasso(alpha=p, tol=0.01)       # training on lasso
    model.fit(X_train, Y_train)
    # print('abc')
    return model, X_train

In [ ]:
lassoB, _ = Lassoreg(42, 40)
print(np.count_nonzero(lassoB.coef_))
lassoD, _ = Lassoreg(158, 60)
print(np.count_nonzero(lassoD.coef_))         # getting top five coefficients by changing alpha
lassoK, _ = Lassoreg(299, 60)
print(np.count_nonzero(lassoK.coef_))

5
5
5


In [ ]:
indexB=[]
for x in lassoB.coef_:
  if x!=0:
    indexB.append(list(lassoB.coef_).index(x))


indexD=[]
for x in lassoD.coef_:
  if x!=0:
    indexD.append(list(lassoD.coef_).index(x))          # getting index for non zero values

indexK=[]
for x in lassoK.coef_:
  if x!=0:
    indexK.append(list(lassoK.coef_).index(x))

In [ ]:
print(indexB)
print(indexD)
print(indexK)           #The features at these column numbers are most important out of 358

[25, 39, 40, 314, 315]
[25, 132, 158, 160, 214]
[161, 230, 232, 247, 303]


In [ ]:
y_pred_lasso_B=Predictmodel(lassoB,42)
y_pred_lasso_D=Predictmodel(lassoD,158)
y_pred_lasso_K=Predictmodel(lassoK,299)

In [ ]:
rmsbombay = (mean_squared_error(Y_bombay_actual, y_pred_lasso_B))
rmsdelhi = (mean_squared_error(Y_delhi_actual, y_pred_lasso_D))
rmskgp = (mean_squared_error(Y_kgp_actual, y_pred_lasso_K))
print("Bombay error:" + str(rmsbombay))
print("Delhi error:" + str(rmsdelhi))
print("Kgp error:" + str(rmskgp))

Bombay error:1029.5747422659927
Delhi error:177.65386470515926
Kgp error:406.0173392249512


## Part 5

*Use Decision Tree on 2010 data to classify each day as 1 or 0 (as given in ZR1). For each day, use the 357-dimensional rainfall vector as feature vector. Report the 10 most discriminative features (i.e. locations)*

In [ ]:
train_vector = mat['ZR1'][0]
test_vector=mat1['ZR'][0]
print(np.shape(Train_main_df))
print(np.shape(train_vector))       #checking the dimensions and getting the vectors ready

(357, 122)
(122,)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
treem=DecisionTreeClassifier(criterion='entropy',random_state=5)
treem.fit(Train_main_df.T,train_vector.T)  # the input shapes must be (122,357) and (122,)  i.e. (num_labels,num_features) for X and (num_labels) for Y

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=5, splitter='best')

In [ ]:
all_feat=treem.feature_importances_

In [ ]:
np.count_nonzero(all_feat)  # how many features have non zero weight/importance

8

In [ ]:
imp_feat=np.nonzero(all_feat)[0]

In [ ]:
imp_feat # col numbers of 8 most important features

array([ 29,  87, 123, 159, 216, 255, 314, 337])

## Part 6

*Use this Decision Tree to classify each day of 2011 as 1 or 0. Report accuracy by comparing with ZR.*

In [ ]:
prediction_tree=treem.predict(Test_main_df1.T)  # predicting on 2011 data

In [ ]:
prediction_tree

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [ ]:
test_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [ ]:
count=0
for i in range(len(test_vector)):
  if prediction_tree[i]==test_vector[i]:          # checking how many values match
    count=count+1

In [ ]:
accuracy=count*100/len(test_vector)
print("Accuracy : ",accuracy," %")      #ACCURACY

Efficiency :  77.04918032786885  %
